name: Update on Push

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - dev
      - main

env:
  BRANCHNAME: ${{ github.REF_NAME }}

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "GITHUB_REF_NAME: ${{env.BRANCHNAME}}"
      - uses: pulumi/actions@v3
        with:
          command: update
          ### SET ORGNAME NAME ACCORDINGLY
          stack-name: ORGNAME/docker-build-deploy/dev
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
